[solution]
name = "gdn-prefill-v1"
definition = "gdn_prefill_qk4_v8_d128_k_last"
author = "KimJangMaengShin"

[build]
language = "python"
entry_point = "main.py::run"
dependencies = ["cutlass", "cuda-python"]
destination_passing_style = false
